### ISSUE TITLE
Data sources ?

### ISSUE THREAD

**Issue by elreviae** [l-portet/coronavirus-data#1]
Bonjour, je souhaiterai avoir un peu plus d'informations concernant la provenance des sources en JSON si possible ?
Actuellement je travail sur une application web connectée html / javascript pour un affichage de la progression du Covid-19.

Je n'ai pas trouvé d'où proviennent vos sources exactement, merci de m'éclairer à ce sujet :)

**Comment by l-portet** [comment]
Salut, je copie les données de coronavirus.app sur ce repo pour eviter d'encombrer le traffic de leur API.

Leurs sources :
- World Health Organization
- National Health Commission of the People's Republic of China
- European Centre for Disease Prevention and Control
- Centers for Disease Control and Prevention
- Coronamap.site
- Taiwan National Health Insurance
- Taiwan Centers for Disease Control
- Health Commission of Hubei Province
- Zhejiang Government
- Health Commission of Guangdong Province
- Health Commission of Hunan
- Health Commission of Chongqing
- Health Commission of Jingxia Province
- Health Commission of Shanghai
- Hainan Daily
- Health Commission of Heilongjiang Province
- Health Commission of Shanxi Province
- Government of the Hong Kong Special Administrative Region
- Taiwan Ministry of Health and Welfare
- BBC News
- Japanese Ministry of Health, Labour and Welfare
- Ministry of Health - Singapore
- Director General of Health Malaysia
- France 24
- Ministry of Health Bavaria
- Emirates News Agency
- Government of Ontario
- Ministry of Health Vietnam
- UK government
- Health Commission of Shanghai
- Health Commission of Shaanxi
- Public health Agency of Sweden
- Fujian Radio & Television Network
- Weibo
- Robert Kock Institut
- MOHW Korea
- John Hopkins University, Center for Systems Science and Engineering
- Worldometers
- BNO News
- Wikipedia
- US Centers for Disease Control and Prevention
- Agence Nationale de Santé Publique en France
- Agences régionales de santé en France
- Ministry of Health & Family Welfare of India
- Secretaría de Salud Federal, Dirección General de Epidemiología (Mexico)
- State of Israel, Ministry of Health
- Gouvernement du Bénin
- Australian Department of Health
- Republic of Kosovo - Ministry of Health
- Ministério da Saúde - Brasil
- Bundesministerium für Gesundheit

**Comment by elreviae** [comment]
Bonjour,
Merci beaucoup pour ce retour d'informations rapide et pour ce travail effectué.
Et bon courage également pour cette période de confinement !
Cordialement
