### ISSUE TITLE
Problème de mise à jour sur map.json

### ISSUE THREAD

**Issue by elreviae** [l-portet/coronavirus-data#2]
Bonjour,
J'ai récemment constaté un problème sur le fichier de data map.json.
Est-ce normal pour le moment ? Peut-être plus de màj futures pour ce jeu de données ?

Cordialement,

Maxime

**Comment by l-portet** [comment]
Le problème sur `map.json` devrait être réglé, les données ont été maj.

**Comment by elreviae** [comment]
Merci beaucoup ! C'est super !
Cordialement
